add parsertype to schema, add open source custom attributes to README
fortify/plugin-api pull request #10
Opened 2022-09-14 16:38 UTC by mfaquan

This is for the Fortify 22.2 release.

2022-09-15 13:09 UTC, thurmon commented on README.md
> +* For SSC to consider issues to be "Open Source", the parser plugin must add the element "&lt;parser-type&gt;DEPENDENCY_SCAN&lt;/parser-type&gt;" to the &lt;issue-parser&gt; element in the plugin's p
```suggestion
* For SSC to consider issues as "Open Source" issues, the parser plugin must add the element "&lt;parser-type&gt;DEPENDENCY_SCAN&lt;/parser-type&gt;" to the &lt;issue-parser&gt; element in the plugin's plugin.xml file.
```

2022-09-15 13:10 UTC, thurmon commented on README.md
> +	- externalId: An ID for the issue, like a CVE ID
```suggestion
	- externalId: An ID, such as a CVE ID, for the issue
```

2022-09-15 14:04 UTC, thurmon commented on README.md
> +	- externalUrl: An external URL for the vulnerability
```suggestion
	- externalUrl: External URL for the vulnerability
```

2022-09-15 14:04 UTC, thurmon commented on README.md
> +	- cwes: Comma-separated list of CWE ID numbers(Only the numbers)
```suggestion
	- cwes: Comma-separated list of CWE IDs (numbers only)
```

2022-09-15 14:06 UTC, thurmon commented on README.md
> +	- componentLicenses: The type of licenses for the vulnerable component
```suggestion
	- componentLicenses: Type of licenses for the vulnerable component
```

2022-09-15 14:09 UTC, thurmon commented on README.md
> +	- invoked:  true/false value for whether or not the analyzed code calls this specific vulnerability
```suggestion
	- invoked:  true/false value for whether or not the analyzed code calls this specific issue
```

2022-09-15 14:09 UTC, thurmon commented on README.md
> +	- controllable: true/false value for whether or not the analyzed code calls this specific vulnerability with user-controlled data
```suggestion
	- controllable: true/false value for whether or not the analyzed code calls this specific issue with user-controlled data
```

2022-09-15 14:10 UTC, thurmon commented on README.md
> +	- evidence: Any supporting evidence that the analyzed code is vulnerable to this specific vulnerability
```suggestion
	- evidence: Any supporting evidence that the analyzed code is vulnerable to this specific issue
```
OR
"Any supporting evidence that the analyzed code is susceptible to this specific issue"

2022-09-15 14:31 UTC, thurmon requested changes
A few edits suggested.

2022-09-15 15:10 UTC, mfaquan commented on README.md
> +	- evidence: Any supporting evidence that the analyzed code is vulnerable to this specific vulnerability
Updated.

2022-09-15 16:56 UTC, arungitan commented
one of the commits says 1.1.  be sure to either squash or update commit to say 1.2.

2022-09-15 17:55 UTC, arungitan commented
also need to update the README.md to make it consistent with versioning and other details.

2022-09-15 18:01 UTC, mfaquan commented
> one of the commits says 1.1. be sure to either squash or update commit to say 1.2.

Version is 1.1.0.  I originally put 1.0.2, but, we decided to bump the minor version and make it 1.1.0.

2022-11-11 09:38 UTC, psmf commented
Superseded by #11

2022-11-11 09:38 UTC, closed without merging